---
title: Comic character
hero_image: images/banner.png
description: Create a superhero design website!
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: You will make
- title: Add the footer to the home page
  completion:
    - engaged
- title: Add the footer to the character page
- title: Show the current year
- title: Build the character form
- title: Show the superhero summary
- title: Let the user edit the summary
# - title: Check the form before creating
- title: Add a light mode switch to the home page
- title: Add a light mode switch to the character page
- title: Save the light mode choice
- title: Control the hero slider
  completion:
    - internal
- title: Challenge
  challenge: true
  completion:
    - external
